In [1]:
import pandas as pds
import numpy as npy

In [2]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Amy', 'Michael', 'Linda'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
print(data_frame_matrix.T)

   a         b        c  d  e
0  1  0.065280      Bob  B  0
1  2  0.467896      Amy  o  1
2  3  0.867549  Michael  b  2
3  4  0.048746    Linda  o  3
         0         1         2         3
a        1         2         3         4
b  0.06528  0.467896  0.867549  0.048746
c      Bob       Amy   Michael     Linda
d        B         o         b         o
e        0         1         2         3

In [5]:
matrix = npy.random.randint(0,100,18).reshape(2,9)
print(matrix)
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
print(data_frame_matrix.describe())

[[26 82 92 53 10 20 11 59 61]
 [58  1 39 76 32 36 39 61 76]]
    0   1   2   3   4   5   6   7   8
0  26  82  92  53  10  20  11  59  61
1  58   1  39  76  32  36  39  61  76
               0          1          2          3          4          5  \
count   2.000000   2.000000   2.000000   2.000000   2.000000   2.000000
mean   42.000000  41.500000  65.500000  64.500000  21.000000  28.000000
std    22.627417  57.275649  37.476659  16.263456  15.556349  11.313708
min    26.000000   1.000000  39.000000  53.000000  10.000000  20.000000
25%    34.000000  21.250000  52.250000  58.750000  15.500000  24.000000
50%    42.000000  41.500000  65.500000  64.500000  21.000000  28.000000
75%    50.000000  61.750000  78.750000  70.250000  26.500000  32.000000
max    58.000000  82.000000  92.000000  76.000000  32.000000  36.000000

              6          7          8
count   2.00000   2.000000   2.000000
mean   25.00000  60.000000  68.500000
std    19.79899   1.414214  10.606602
min    11.00000  59.000000  61.000000
25%    18.00000  59.500000  64.750000
50%    25.00000  60.000000  68.500000
75%    32.00000  60.500000  72.250000
max    39.00000  61.000000  76.000000

In [6]:
matrix = npy.arange(1, 19).reshape(2,9)
print(matrix)
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
data_frame_matrix = pds.DataFrame(matrix, index=list("甲乙"), columns = list("ABCDEFGHI"))
print(data_frame_matrix)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]
    0   1   2   3   4   5   6   7   8
0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18
    A   B   C   D   E   F   G   H   I
甲   1   2   3   4   5   6   7   8   9
乙  10  11  12  13  14  15  16  17  18

In [7]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Amy', 'Michael', 'Linda'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}

data_frame_matrix = pds.DataFrame(matrix)
print(matrix)
renew_index = {"a": "x", "d": "y"}
data_frame_matrix = data_frame_matrix.rename(renew_index, axis=1) #axis=0
print(data_frame_matrix)

{'a': [1, 2, 3, 4], 'b': array([0.11939354, 0.8722508 , 0.26642631, 0.73970549]), 'c': ['Bob', 'Amy', 'Michael', 'Linda'], 'd': ['B', 'o', 'b', 'o'], 'e': 0    0
1    1
2    2
3    3
dtype: int64}
   x         b        c  y  e
0  1  0.119394      Bob  B  0
1  2  0.872251      Amy  o  1
2  3  0.266426  Michael  b  2
3  4  0.739705    Linda  o  3

In [8]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Amy', 'Michael', 'Linda'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}

data_frame_matrix = pds.DataFrame(matrix)

print(data_frame_matrix)
renew_index = {1: "one", 0: "zero"}
data_frame_matrix = data_frame_matrix.rename(renew_index, axis=0)
print(data_frame_matrix)

   a         b        c  d  e
0  1  0.122981      Bob  B  0
1  2  0.549562      Amy  o  1
2  3  0.818088  Michael  b  2
3  4  0.391249    Linda  o  3
      a         b        c  d  e
zero  1  0.122981      Bob  B  0
one   2  0.549562      Amy  o  1
2     3  0.818088  Michael  b  2
3     4  0.391249    Linda  o  3

In [7]:
dates_index = pds.date_range("20220101", periods=4)
print(dates_index)
data_frame_matrix.index = dates_index
print(data_frame_matrix)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04'], dtype='datetime64[ns]', freq='D')
            a         b        c  d  e
2022-01-01  1  0.485041      Bob  B  0
2022-01-02  2  0.396374      Amy  o  1
2022-01-03  3  0.756491  Michael  b  2
2022-01-04  4  0.303063    Linda  o  3

In [8]:
matrix = {
    "A": npy.arange(1,31),
    "B": npy.arange(31,61),
    "C": npy.arange(61,91),
    "D": npy.arange(91,121),
    "E": npy.arange(121,151),
}
data_frame_matrix = pds.DataFrame(matrix)
print(data_frame_matrix)
print(data_frame_matrix.head(2))
print(data_frame_matrix.tail()) #(3)

     A   B   C    D    E
0    1  31  61   91  121
1    2  32  62   92  122
2    3  33  63   93  123
3    4  34  64   94  124
4    5  35  65   95  125
5    6  36  66   96  126
6    7  37  67   97  127
7    8  38  68   98  128
8    9  39  69   99  129
9   10  40  70  100  130
10  11  41  71  101  131
11  12  42  72  102  132
12  13  43  73  103  133
13  14  44  74  104  134
14  15  45  75  105  135
15  16  46  76  106  136
16  17  47  77  107  137
17  18  48  78  108  138
18  19  49  79  109  139
19  20  50  80  110  140
20  21  51  81  111  141
21  22  52  82  112  142
22  23  53  83  113  143
23  24  54  84  114  144
24  25  55  85  115  145
25  26  56  86  116  146
26  27  57  87  117  147
27  28  58  88  118  148
28  29  59  89  119  149
29  30  60  90  120  150
   A   B   C   D    E
0  1  31  61  91  121
1  2  32  62  92  122
     A   B   C    D    E
25  26  56  86  116  146
26  27  57  87  117  147
27  28  58  88  118  148
28  29  59  89  119  149
29  30  60  90  120  150

In [ ]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
cols = data_frame.columns.tolist()
col_index = '活死'
cols.insert(2, col_index)
data_frame[col_index] = data_frame.Survived.apply(lambda z:'活'if z else'死')
data_frame.loc[:10, cols]

,PassengerId,Survived,活死,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,死,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,活,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,活,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,活,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,死,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,死,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,死,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,死,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,活,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,活,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,活,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [10]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
print(data_frame)
cols = ['Name','Age']
data_frame.drop(cols, axis=1, inplace=True)
print(data_frame)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
     PassengerId  Survived  Pclass     Sex  SibSp  Parch            Ticket  \
0              1         0       3    male      1      0         A/5 21171
1              2         1       1  female      1      0          PC 17599
2              3         1       3  female      0      0  STON/O2. 3101282
3              4         1       1  female      1      0            113803
4              5         0       3    male      0      0            373450
..           ...       ...     ...     ...    ...    ...               ...
886          887         0       2    male      0      0            211536
887          888         1       1  female      0      0            112053
888          889         0       3  female      1      2        W./C. 6607
889          890         1       1    male      0      0            111369
890          891         0       3    male      0      0            370376

        Fare Cabin Embarked
0     7.2500   NaN        S
1    71.2833   C85        C
2     7.9250   NaN        S
3    53.1000  C123        S
4     8.0500   NaN        S
..       ...   ...      ...
886  13.0000   NaN        S
887  30.0000   B42        S
888  23.4500   NaN        S
889  30.0000  C148        C
890   7.7500   NaN        Q

[891 rows x 10 columns]

In [11]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
data_frame_train = data_frame.sample(frac=0.7)
display(data_frame_train)
data_frame_test = data_frame.drop(data_frame_train.index)
display(data_frame_test)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.0,0,0,PC 17593,79.2000,B82 B84,C
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
594,595,0,2,"Chapman, Mr. John Henry",male,37.0,1,0,SC/AH 29037,26.0000,NaN,S
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
203,204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
print(data_frame)
data_frame_types = {"Survived": "bool"}
data_frame = pds.read_csv('http://bit.ly/kaggletrain', dtype=data_frame_types)
print(data_frame)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
     PassengerId  Survived  Pclass  \
0              1     False       3
1              2      True       1
2              3      True       3
3              4      True       1
4              5     False       3
..           ...       ...     ...
886          887     False       2
887          888      True       1
888          889     False       3
889          890      True       1
890          891     False       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [13]:
data_frame = pds.read_csv('http://bit.ly/kaggletrain')
print(data_frame.iloc[:50, 0:4])  #取0-49列的0-3欄
print(data_frame.iloc[:50, ::-1])  #col反向顯示
print(data_frame.iloc[::-1, 0:4])  #row反向顯示

    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3
11           12         1       1
12           13         0       3
13           14         0       3
14           15         0       3
15           16         1       2
16           17         0       3
17           18         1       2
18           19         0       3
19           20         1       3
20           21         0       2
21           22         1       2
22           23         1       3
23           24         1       1
24           25         0       3
25           26         1       3
26           27         0       3
27           28         0       1
28           29         1       3
29           30         0       3
30           31         0       1
31           32         1       1
32           33         1       3
33           34         0       2
34           35         0       1
35           36         0       1
36           37         1       3
37           38         0       3
38           39         0       3
39           40         1       3
40           41         0       3
41           42         0       2
42           43         0       3
43           44         1       2
44           45         1       3
45           46         0       3
46           47         0       3
47           48         1       3
48           49         0       3
49           50         0       3

                                                 Name
0                             Braund, Mr. Owen Harris
1   Cumings, Mrs. John Bradley (Florence Briggs Th...
2                              Heikkinen, Miss. Laina
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                            Allen, Mr. William Henry
5                                    Moran, Mr. James
6                             McCarthy, Mr. Timothy J
7                      Palsson, Master. Gosta Leonard
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                 Nasser, Mrs. Nicholas (Adele Achem)
10                    Sandstrom, Miss. Marguerite Rut
11                           Bonnell, Miss. Elizabeth
12                     Saundercock, Mr. William Henry
13                        Andersson, Mr. Anders Johan
14               Vestrom, Miss. Hulda Amanda Adolfina
15                   Hewlett, Mrs. (Mary D Kingcome)
16                               Rice, Master. Eugene
17                       Williams, Mr. Charles Eugene
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                            Masselmani, Mrs. Fatima
20                               Fynney, Mr. Joseph J
21                              Beesley, Mr. Lawrence
22                        McGowan, Miss. Anna "Annie"
23                       Sloper, Mr. William Thompson
24                      Palsson, Miss. Torborg Danira
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
26                            Emir, Mr. Farred Chehab
27                     Fortune, Mr. Charles Alexander
28                      O'Dwyer, Miss. Ellen "Nellie"
29                                Todoroff, Mr. Lalio
30                           Uruchurtu, Don. Manuel E
31     Spencer, Mrs. William Augustus (Marie Eugenie)
32                           Glynn, Miss. Mary Agatha
33                              Wheadon, Mr. Edward H
34                            Meyer, Mr. Edgar Joseph
35                     Holverson, Mr. Alexander Oskar
36                                   Mamee, Mr. Hanna
37                           Cann, Mr. Ernest Charles
38                 Vander Planke, Miss. Augusta Maria
39                        Nicola-Yarred, Miss. Jamila
40     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
41  Turpin, Mrs. William John Robert (Dorothy Ann ...
42                                Kraeff, Mr. Theodor
43           Laroche, Miss. Simonne Marie Anne Andree
44                      Devaney, Miss. Margaret Delia
45                           Rogers, Mr. William John
46                                  Lennon, Mr. Denis
47                          O'Driscoll, Miss. Bridget
48                                Samaan, Mr. Youssef
49      Arnold-Franchi, Mrs. Josef (Josefine Franchi)
   Embarked        Cabin      Fare            Ticket  Parch  SibSp   Age  \
0         S          NaN    7.2500         A/5 21171      0      1  22.0
1         C          C85   71.2833          PC 17599      0      1  38.0
2         S          NaN    7.9250  STON/O2. 3101282      0      0  26.0
3         S         C123   53.1000            113803      0      1  35.0
4         S          NaN    8.0500            373450      0      0  35.0
5         Q          NaN    8.4583            330877      0      0   NaN
6         S          E46   51.8625             17463      0      0  54.0
7         S          NaN   21.0750            349909      1      3   2.0
8         S          NaN   11.1333            347742      2      0  27.0
9         C          NaN   30.0708            237736      0      1  14.0
10        S           G6   16.7000           PP 9549      1      1   4.0
11        S         C103   26.5500            113783      0      0  58.0
12        S          NaN    8.0500         A/5. 2151      0      0  20.0
13        S          NaN   31.2750            347082      5      1  39.0
14        S          NaN    7.8542            350406      0      0  14.0
15        S          NaN   16.0000            248706      0      0  55.0
16        Q          NaN   29.1250            382652      1      4   2.0
17        S          NaN   13.0000            244373      0      0   NaN
18        S          NaN   18.0000            345763      0      1  31.0
19        C          NaN    7.2250              2649      0      0   NaN
20        S          NaN   26.0000            239865      0      0  35.0
21        S          D56   13.0000            248698      0      0  34.0
22        Q          NaN    8.0292            330923      0      0  15.0
23        S           A6   35.5000            113788      0      0  28.0
24        S          NaN   21.0750            349909      1      3   8.0
25        S          NaN   31.3875            347077      5      1  38.0
26        C          NaN    7.2250              2631      0      0   NaN
27        S  C23 C25 C27  263.0000             19950      2      3  19.0
28        Q          NaN    7.8792            330959      0      0   NaN
29        S          NaN    7.8958            349216      0      0   NaN
30        C          NaN   27.7208          PC 17601      0      0  40.0
31        C          B78  146.5208          PC 17569      0      1   NaN
32        Q          NaN    7.7500            335677      0      0   NaN
33        S          NaN   10.5000        C.A. 24579      0      0  66.0
34        C          NaN   82.1708          PC 17604      0      1  28.0
35        S          NaN   52.0000            113789      0      1  42.0
36        C          NaN    7.2292              2677      0      0   NaN
37        S          NaN    8.0500        A./5. 2152      0      0  21.0
38        S          NaN   18.0000            345764      0      2  18.0
39        C          NaN   11.2417              2651      0      1  14.0
40        S          NaN    9.4750              7546      0      1  40.0
41        S          NaN   21.0000             11668      0      1  27.0
42        C          NaN    7.8958            349253      0      0   NaN
43        C          NaN   41.5792     SC/Paris 2123      2      1   3.0
44        Q          NaN    7.8792            330958      0      0  19.0
45        S          NaN    8.0500   S.C./A.4. 23567      0      0   NaN
46        Q          NaN   15.5000            370371      0      1   NaN
47        Q          NaN    7.7500             14311      0      0   NaN
48        C          NaN   21.6792              2662      0      2   NaN
49        S          NaN   17.8000            349237      0      1  18.0

       Sex                                               Name  Pclass  \
0     male                            Braund, Mr. Owen Harris       3
1   female  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2   female                             Heikkinen, Miss. Laina       3
3   female       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4     male                           Allen, Mr. William Henry       3
5     male                                   Moran, Mr. James       3
6     male                            McCarthy, Mr. Timothy J       1
7     male                     Palsson, Master. Gosta Leonard       3
8   female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3
9   female                Nasser, Mrs. Nicholas (Adele Achem)       2
10  female                    Sandstrom, Miss. Marguerite Rut       3
11  female                           Bonnell, Miss. Elizabeth       1
12    male                     Saundercock, Mr. William Henry       3
13    male                        Andersson, Mr. Anders Johan       3
14  female               Vestrom, Miss. Hulda Amanda Adolfina       3
15  female                   Hewlett, Mrs. (Mary D Kingcome)        2
16    male                               Rice, Master. Eugene       3
17    male                       Williams, Mr. Charles Eugene       2
18  female  Vander Planke, Mrs. Julius (Emelia Maria Vande...       3
19  female                            Masselmani, Mrs. Fatima       3
20    male                               Fynney, Mr. Joseph J       2
21    male                              Beesley, Mr. Lawrence       2
22  female                        McGowan, Miss. Anna "Annie"       3
23    male                       Sloper, Mr. William Thompson       1
24  female                      Palsson, Miss. Torborg Danira       3
25  female  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...       3
26    male                            Emir, Mr. Farred Chehab       3
27    male                     Fortune, Mr. Charles Alexander       1
28  female                      O'Dwyer, Miss. Ellen "Nellie"       3
29    male                                Todoroff, Mr. Lalio       3
30    male                           Uruchurtu, Don. Manuel E       1
31  female     Spencer, Mrs. William Augustus (Marie Eugenie)       1
32  female                           Glynn, Miss. Mary Agatha       3
33    male                              Wheadon, Mr. Edward H       2
34    male                            Meyer, Mr. Edgar Joseph       1
35    male                     Holverson, Mr. Alexander Oskar       1
36    male                                   Mamee, Mr. Hanna       3
37    male                           Cann, Mr. Ernest Charles       3
38  female                 Vander Planke, Miss. Augusta Maria       3
39  female                        Nicola-Yarred, Miss. Jamila       3
40  female     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)       3
41  female  Turpin, Mrs. William John Robert (Dorothy Ann ...       2
42    male                                Kraeff, Mr. Theodor       3
43  female           Laroche, Miss. Simonne Marie Anne Andree       2
44  female                      Devaney, Miss. Margaret Delia       3
45    male                           Rogers, Mr. William John       3
46    male                                  Lennon, Mr. Denis       3
47  female                          O'Driscoll, Miss. Bridget       3
48    male                                Samaan, Mr. Youssef       3
49  female      Arnold-Franchi, Mrs. Josef (Josefine Franchi)       3

    Survived  PassengerId
0          0            1
1          1            2
2          1            3
3          1            4
4          0            5
5          0            6
6          0            7
7          0            8
8          1            9
9          1           10
10         1           11
11         1           12
12         0           13
13         0           14
14         0           15
15         1           16
16         0           17
17         1           18
18         0           19
19         1           20
20         0           21
21         1           22
22         1           23
23         1           24
24         0           25
25         1           26
26         0           27
27         0           28
28         1           29
29         0           30
30         0           31
31         1           32
32         1           33
33         0           34
34         0           35
35         0           36
36         1           37
37         0           38
38         0           39
39         1           40
40         0           41
41         0           42
42         0           43
43         1           44
44         1           45
45         0           46
46         0           47
47         1           48
48         0           49
49         0           50
     PassengerId  Survived  Pclass  \
890          891         0       3
889          890         1       1
888          889         0       3
887          888         1       1
886          887         0       2
..           ...       ...     ...
4              5         0       3
3              4         1       1
2              3         1       3
1              2         1       1
0              1         0       3

                                                  Name
890                                Dooley, Mr. Patrick
889                              Behr, Mr. Karl Howell
888           Johnston, Miss. Catherine Helen "Carrie"
887                       Graham, Miss. Margaret Edith
886                              Montvila, Rev. Juozas
..                                                 ...
4                             Allen, Mr. William Henry
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
2                               Heikkinen, Miss. Laina
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
0                              Braund, Mr. Owen Harris

[891 rows x 4 columns]

In [14]:
matrix = {
    "a": [1, 2, 3, 4],
    "b": npy.random.random(4),
    "c": ['Bob', 'Linda', 'Michael', 'Amy'],
    "d": list('Bobo'),
    "e": pds.Series(range(4))
}

data_frame = pds.DataFrame(matrix)
print(data_frame)
print(data_frame.sort_values(by=['d']))
print(data_frame.sort_values(by=['d'], ascending=False))
print(data_frame.sort_values(by=['d', 'c']))

   a         b        c  d  e
0  1  0.207116      Bob  B  0
1  2  0.688689    Linda  o  1
2  3  0.544305  Michael  b  2
3  4  0.006267      Amy  o  3
   a         b        c  d  e
0  1  0.207116      Bob  B  0
2  3  0.544305  Michael  b  2
1  2  0.688689    Linda  o  1
3  4  0.006267      Amy  o  3
   a         b        c  d  e
1  2  0.688689    Linda  o  1
3  4  0.006267      Amy  o  3
2  3  0.544305  Michael  b  2
0  1  0.207116      Bob  B  0
   a         b        c  d  e
0  1  0.207116      Bob  B  0
2  3  0.544305  Michael  b  2
3  4  0.006267      Amy  o  3
1  2  0.688689    Linda  o  1